name: nspectra
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::vcftools
  - bioconda::bedtools
  - bioconda::plink=1.90
  - python=3.10
  - pip
  - bioconda::vcflib==1.0.3
  - bioconda::java-jdk
  - bioconda::shapeit4
  - bioconda::shapeit5
  - bioconda::ucsc-fatotwobit 
  - bioconda::ucsc-twobitinfo 
  - matplotlib
  - numpy
  - pandas
  - pysam
  - java-jdk=8.0.92
  - bioconda::perl-bioperl 
  - bioconda::perl-bio-db-hts 
  - bioconda::tabix
  - bioconda::tabixpp=1.1.0
  - conda-forge::r-base>=4.1.0
  - conda-forge::r-cowplot
  - conda-forge::r-tidyverse
  - conda-forge::r-reshape2
  - conda-forge::r-ggfortify
  - conda-forge::r-ggforce
  - conda-forge::r-lazyeval
  - conda-forge::r-plyr
  - bioconda::ucsc-bigwigtobedgraph
  - bioconda::phast=1.5
  - pip:
    - mutyper
    - mushi
