name: nspectra
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::vcftools
  - bioconda::bedtools
  - bioconda::plink=1.90
  - bioconda::ensembl-vep
  - python=3.7
  - pip
  - bioconda::vcflib
  - bioconda::java-jdk
  - bioconda::shapeit4
  - bioconda::ucsc-fatotwobit 
  - bioconda::ucsc-twobitinfo 
  - matplotlib
  - meryl
  - numpy
  - pandas
  - java-jdk=8.0.92
  - bioconda::perl-bioperl 
  - bioconda::perl-bio-db-hts 
  - bioconda::tabix
  - r::r-base=4.1.0
  - r::r-cowplot
  - r::r-tidyverse
  - r::r-reshape2
  - r::r-ggfortify
  - r::r-ggforce
  - r::r-lazyeval>0.2.2
  - r::r-plyr>1.8.6
  - bioconda::ucsc-bigwigtobedgraph
  - bioconda::phast=1.5
  - pip:
    - mutyper
    - mushi
