name: nspectra
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::vcftools
  - bioconda::bedtools
  - bioconda::plink=1.90
  - python=3.10
  - pysam
  - pip
  - bioconda::vcflib=1.0.3
  - bioconda::tabixpp=1.1.0
  - bioconda::java-jdk
  - bioconda::shapeit4
  - bioconda::ucsc-fatotwobit 
  - bioconda::ucsc-twobitinfo 
  - bioconda::ucsc-bigwigtobedgraph
  - bioconda::phast=1.5
  - pip:
    - mutyper
