name: phast
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::bedtools
  - python=3.8
  - bioconda::ucsc-bigwigtobedgraph
  - bioconda::ucsc-wigtobigwig
  - bioconda::phast=1.5
  - pip:
    - mutyper
